FROM python:3.12-slim-bookworm
 
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
 
WORKDIR /app
 
COPY pyproject.toml .
RUN uv sync --no-dev
 
COPY src/ src/
 
EXPOSE 8080
 
ENTRYPOINT ["uv", "run", "uvicorn"]
CMD ["--app-dir", "src", "--host", "0.0.0.0", "--port", "8080", "main:app"]